"""userprofile model bio field added

Revision ID: 4e0e565b24a1
Revises: 74456ed3ab83
Create Date: 2025-01-30 16:28:06.203635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e0e565b24a1'
down_revision: Union[str, None] = '74456ed3ab83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('bio', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'bio')
    # ### end Alembic commands ###
