"""user group model add with m2m relationship primary field declare and unique contsraint

Revision ID: 4e92747c7761
Revises: b956d0b42a3f
Create Date: 2025-01-31 17:30:17.015076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e92747c7761'
down_revision: Union[str, None] = 'b956d0b42a3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_group_id_unique_pair', 'user_group_association', ['user_id', 'group_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_group_id_unique_pair', 'user_group_association', type_='unique')
    # ### end Alembic commands ###
