"""user group model add with m2m relationship primary field declare

Revision ID: b956d0b42a3f
Revises: e5d81d114243
Create Date: 2025-01-31 17:22:22.061734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b956d0b42a3f'
down_revision: Union[str, None] = 'e5d81d114243'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_group_association', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_group_association', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_group_association', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_group_association', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
