"""user group model add with m2m relationship primary field declare and unique contsraint

Revision ID: fafc524eea36
Revises: 4e92747c7761
Create Date: 2025-01-31 17:35:14.214920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fafc524eea36'
down_revision: Union[str, None] = '4e92747c7761'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_group_id_unique_pair', 'user_group_association', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_group_id_unique_pair', 'user_group_association', ['user_id', 'group_id'])
    # ### end Alembic commands ###
